//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1ConLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alquiler_de_espacio
    {
        public int Alquiler_evento { get; set; }
        public string Nombre_del_evento { get; set; }
        public int Cantidad_de_asistentes { get; set; }
        public System.DateTime Fecha_del_evento { get; set; }
        public System.TimeSpan Hora_del_evento { get; set; }
        public Nullable<int> Encargado { get; set; }
        public Nullable<int> Show { get; set; }
    
        public virtual Encargado_del_evento Encargado_del_evento { get; set; }
        public virtual Show_a_presentar Show_a_presentar { get; set; }
    }
}
