//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1ConLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Show_a_presentar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Show_a_presentar()
        {
            this.Alquiler_de_espacio = new HashSet<Alquiler_de_espacio>();
        }
    
        public int Show { get; set; }
        public string Nombre_show { get; set; }
        public string Descripcion { get; set; }
        public decimal Costo_por_hora { get; set; }
        public Nullable<int> Tipo_show { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alquiler_de_espacio> Alquiler_de_espacio { get; set; }
        public virtual Tipo_de_show_a_presentar Tipo_de_show_a_presentar { get; set; }
    }
}
