//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1ConLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_de_show_a_presentar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tipo_de_show_a_presentar()
        {
            this.Show_a_presentar = new HashSet<Show_a_presentar>();
        }
    
        public int Tipo_show { get; set; }
        public string Nombre_tipo { get; set; }
        public string Descripcion_tipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Show_a_presentar> Show_a_presentar { get; set; }
    }
}
